//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realXP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seat
    {
        public int seat_id { get; set; }
        public int camera_id { get; set; }
        public int venue_id { get; set; }
        public int seat_capacity { get; set; }
        public Nullable<int> seat_number { get; set; }
        public string seat_row { get; set; }
        public string seat_section { get; set; }
        public string seat_description { get; set; }
        public string seat_view_image { get; set; }
    
        public virtual camera camera { get; set; }
        public virtual venue venue { get; set; }
    }
}
