//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realXP
{
    using System;
    using System.Collections.Generic;
    
    public partial class camera
    {
        public int camera_id { get; set; }
        public string camera_brand { get; set; }
        public string camera_model { get; set; }
        public int camera_max_seats { get; set; }
        public int camera_resolution_x { get; set; }
        public int camera_resolution_y { get; set; }
        public byte camera_has_audio { get; set; }
        public int camera_fps { get; set; }
    }
}
