//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realXP
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_seats
    {
        public int event_seat_id { get; set; }
        public int event_id { get; set; }
        public int seat_id { get; set; }
        public int event_seat_sell_capacity { get; set; }
        public decimal event_seat_price { get; set; }
    }
}
