//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realXP
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_logs
    {
        public int user_logs_id { get; set; }
        public int user_id { get; set; }
        public string users_logs_action { get; set; }
        public System.DateTime users_logs_timestamp { get; set; }
    }
}
