//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realXP
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_addresses
    {
        public int user_address_id { get; set; }
        public int user_id { get; set; }
        public string user_address_name { get; set; }
        public string user_address_country { get; set; }
        public string user_address_city { get; set; }
        public string user_address_state { get; set; }
        public string user_address_line1 { get; set; }
        public string user_address_line2 { get; set; }
        public string user_address_line3 { get; set; }
        public string user_address_line4 { get; set; }
        public string user_address_postcode { get; set; }
    }
}
