//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realXP
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_purchases
    {
        public int user_purchase_id { get; set; }
        public int event_seats_id { get; set; }
        public int payment_id { get; set; }
        public System.DateTime user_purchase_timestamp { get; set; }
        public int user_id { get; set; }
    }
}
