//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realXP
{
    using System;
    using System.Collections.Generic;
    
    public partial class venue
    {
        public int venue_id { get; set; }
        public string venue_name { get; set; }
        public string venue_country { get; set; }
        public string venue_city { get; set; }
        public string venue_state { get; set; }
        public string venue_address_1 { get; set; }
        public string venue_address_2 { get; set; }
        public string venue_address_3 { get; set; }
        public string venue_postcode { get; set; }
        public string venue_image { get; set; }
    }
}
