//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realXP
{
    using System;
    using System.Collections.Generic;
    
    public partial class venue_reviews
    {
        public int venue_review_id { get; set; }
        public int venue_id { get; set; }
        public int user_id { get; set; }
        public string venue_review_review { get; set; }
        public Nullable<byte> venue_review_rating { get; set; }
    }
}
