//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realxp
{
    using System;
    using System.Collections.Generic;
    
    public partial class liveevent
    {
        public liveevent()
        {
            this.user_purchase = new HashSet<user_purchase>();
        }
    
        public int liveeventID { get; set; }
        public int venueID { get; set; }
        public System.DateTime liveevent_start_time { get; set; }
        public System.DateTime liveevent_end_time { get; set; }
        public string liveevent_name { get; set; }
        public string liveevent_description { get; set; }
        public string liveevent_image { get; set; }
    
        public virtual venue venue { get; set; }
        public virtual ICollection<user_purchase> user_purchase { get; set; }
    }
}
