//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realxp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class realxpEntities : DbContext
    {
        public realxpEntities()
            : base("name=realxpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<camera> cameras { get; set; }
        public virtual DbSet<seat> seats { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<user_address> user_address { get; set; }
        public virtual DbSet<venue> venues { get; set; }
        public virtual DbSet<venue_review> venue_review { get; set; }
        public virtual DbSet<liveevent> liveevents { get; set; }
        public virtual DbSet<user_purchase> user_purchase { get; set; }
    }
}
