//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realxp
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_purchase
    {
        public int user_purchaseID { get; set; }
        public int userID { get; set; }
        public int liveeventID { get; set; }
        public int seatID { get; set; }
        public System.DateTime user_purchase_timestamp { get; set; }
    
        public virtual liveevent liveevent { get; set; }
        public virtual seat seat { get; set; }
        public virtual user user { get; set; }
    }
}
