//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realxp
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.user_address = new HashSet<user_address>();
            this.venue_review = new HashSet<venue_review>();
            this.user_purchase = new HashSet<user_purchase>();
        }
    
        public int userID { get; set; }
        public string user_email { get; set; }
        public string user_password_hash { get; set; }
        public string user_password_salt { get; set; }
        public string user_firstname { get; set; }
        public string user_lastname { get; set; }
    
        public virtual ICollection<user_address> user_address { get; set; }
        public virtual ICollection<venue_review> venue_review { get; set; }
        public virtual ICollection<user_purchase> user_purchase { get; set; }
    }
}
