//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realxp
{
    using System;
    using System.Collections.Generic;
    
    public partial class venue_review
    {
        public int venue_reviewID { get; set; }
        public int venueID { get; set; }
        public int userID { get; set; }
        public string venue_review_review { get; set; }
        public Nullable<byte> venue_review_rating { get; set; }
    
        public virtual user user { get; set; }
        public virtual venue venue { get; set; }
    }
}
