//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realxp
{
    using System;
    using System.Collections.Generic;
    
    public partial class venue
    {
        public venue()
        {
            this.seats = new HashSet<seat>();
            this.venue_review = new HashSet<venue_review>();
            this.liveevents = new HashSet<liveevent>();
        }
    
        public int venueID { get; set; }
        public string venue_name { get; set; }
        public string venue_country { get; set; }
        public string venue_city { get; set; }
        public string venue_state { get; set; }
        public string venue_address_1 { get; set; }
        public string venue_address_2 { get; set; }
        public string venue_address_3 { get; set; }
        public string venue_postcode { get; set; }
        public string venue_image { get; set; }
    
        public virtual ICollection<seat> seats { get; set; }
        public virtual ICollection<venue_review> venue_review { get; set; }
        public virtual ICollection<liveevent> liveevents { get; set; }
    }
}
