//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realXP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public int event_id { get; set; }
        public int venue_id { get; set; }
        public System.DateTime event_start_time { get; set; }
        public System.DateTime event_end_time { get; set; }
        public string event_name { get; set; }
        public string event_description { get; set; }
        public string event_image { get; set; }
    }
}
