//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realXP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class realxpDB : DbContext
    {
        public realxpDB()
            : base("name=realxpDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<camera> cameras { get; set; }
        public virtual DbSet<event_seats> event_seats { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<payment_methods> payment_methods { get; set; }
        public virtual DbSet<payment> payments { get; set; }
        public virtual DbSet<seat> seats { get; set; }
        public virtual DbSet<user_addresses> user_addresses { get; set; }
        public virtual DbSet<user_logs> user_logs { get; set; }
        public virtual DbSet<user_purchases> user_purchases { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<venue_reviews> venue_reviews { get; set; }
        public virtual DbSet<venue> venues { get; set; }
    }
}
