//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace realXP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int user_id { get; set; }
        public string user_email { get; set; }
        public string user_password_hash { get; set; }
        public string user_password_salt { get; set; }
        public string user_firstname { get; set; }
        public string user_lastname { get; set; }
    }
}
